In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn
from sqlalchemy import create_engine

## Data Preprocessing
For practice we perform Data Preprocessing in both python and postgresql. We first store the csv file as a table in postgresql.

In [6]:
df = pd.read_csv("diabetes.csv")
connection = create_engine("postgresql://postgres:1234512345@172.20.160.1:5432/diabetes")
df.to_sql("diabetes", con = connection, if_exists = 'replace', index = False)

768

In [58]:
# View the first 3 rows in the DataFrame 
df.head(3)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35.0,0,33.6,0.627,50,1
1,1,85,66,29.0,0,26.6,0.351,31,0
2,8,183,64,0.0,0,23.3,0.672,32,1

In [ ]:
# View 5 random samples from the DataFrame
df.sample(5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
653,2,120,54,0.0,0,26.8,0.455,27,0
589,0,73,0,0.0,0,21.1,0.342,25,0
330,8,118,72,19.0,0,23.1,1.476,46,0
156,2,99,52,15.0,94,24.6,0.637,21,0
469,6,154,78,41.0,140,46.1,0.571,27,0

In [90]:
# General information about the DataFrame
print(f"Dataset has {df.shape[0]} samples. total columns of {df.shape[1]}"
      f" and {df.shape[1] - 1} features\n\n")
df.info()

Dataset has 768 samples. total columns of 9 and 8 features


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             762 non-null    float64
 4   Insulin                   768 non-null    int64
 5   BMI                       763 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(3), int64(6)
memory usage: 54.1 KB

In [95]:
# Statistics of the DataFrame
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,762.000000,768.000000,763.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.578740,79.799479,31.990695,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.937451,115.244002,7.905060,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [ ]:
# Values counts for the results column
df["Outcome"].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [99]:
# Number of the duplicated rows
print(df.duplicated().sum())

0

In [101]:
# Number of Null values in each column
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               6
Insulin                     0
BMI                         5
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
# What percentage of the rows are missing values
df.isna().mean() * 100

Pregnancies                 0.000000
Glucose                     0.000000
BloodPressure               0.000000
SkinThickness               0.781250
Insulin                     0.000000
BMI                         0.651042
DiabetesPedigreeFunction    0.000000
Age                         0.000000
Outcome                     0.000000
dtype: float64

In [105]:
## Dealing With Missing Values